version: "3.8"
services:
  app-jenkins:
    build: lab-jenkins
    volumes:
      - ./src/:/home/app
    command: ["tail", "-f", "/dev/null"]
  app-kafka:
    build: lab-kafka
    volumes:
      - ./src/:/home/app
    command: ["tail", "-f", "/dev/null"]
