---
- name: "AWS - setup kafka cluster"
  hosts: tag_Name_lab_kafka_node_{{ node_number }}
  become: true
  remote_user: ec2-user

  vars:
    node_number: "{{ node_number }}"
    ansible_python_interpreter: /usr/bin/python3.7

  tasks:
  - name: Create /data/kafka volume dir and setup permissions
    file:
      path: /data/kafka
      state: directory
      owner: 1001
      group: 1001
      mode: 0775
  - name: Create /data/zookeeper volume dir and setup permissions
    file:
      path: /data/zookeeper
      state: directory
      owner: 1001
      group: 1001
      mode: 0775
  - name: Copy `kafka/docker-compose-node-<node_number>.yaml` docker-compose file
    copy:
      src: "kafka/docker-compose-node-{{ node_number }}.yaml"
      dest: /home/ec2-user/docker-compose.yaml
      owner: ec2-user
      group: ec2-user
      mode: 0644
  - name: Install urllib3 library
    pip:
      name: urllib3
      state: present
      version: 1.26.6
  - name: Install docker library
    pip:
      name: docker
      state: present
  - name: Install docker-compose library
    pip:
      name: docker-compose
      state: present
  - name: copy .env file
    copy:
      src: .env
      dest: /home/ec2-user/.env
      owner: ec2-user
      group: ec2-user
      mode: 0644
  - name: Verify Docker Compose file exists
    stat:
      path: "/home/ec2-user/docker-compose.yaml"
    register: docker_compose_file
  - name: deploy and start Docker Compose stack
    community.docker.docker_compose:
      project_src: /home/ec2-user
      files:
        - docker-compose.yaml
    when: docker_compose_file.stat.exists
