---
  - name: install Apache
    hosts: all
    become: yes
    tasks: 
      - name: Install the latest version of Apache
        ansible.builtin.yum:
          name: httpd
          state: latest
      - name: Start Apache service
        service:
          name: httpd
          state: started
          enabled: true
      - name: Install lynx
        ansible.builtin.yum:
          name: lynx
          state: latest
