apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: lab
  region: eu-central-1
managedNodeGroups:
- name: primary-1-18
  instanceType: t2.small
  iam:
    withAddonPolicies:
      albIngress: true
  minSize: 1
  maxSize: 3
  spot: true
