# kafka cluster node 1
version: '2'

services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    volumes:
      - '/data/zookeeper:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,${KAFKA_NODE_2_PRIVATE_IP}:2888:3888
      - ZOO_HEAP_SIZE=512
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - '/data/kafka:/bitnami/kafka'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://${KAFKA_NODE_1_PRIVATE_IP}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=EXTERNAL
    depends_on:
      - zookeeper
