# kafka cluster node 2
version: '2'

services:
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - '/var/log/kafka:/opt/bitnami/kafka/logs'
      - '/data/kafka:/bitnami/kafka'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=${KAFKA_NODE_1_PRIVATE_IP}:2181
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://${KAFKA_NODE_2_PRIVATE_IP}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=EXTERNAL
