name: Terraform and Ansible Workflow

on:
  workflow_call:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tfpath:
        description: 'terraform source dir'
        required: false
        default: 'lab-kafka/terraform'
      skip_terraform:
        description: 'When TRUE terraform job will be skipped'
        type: boolean
        default: false
      destroy:
        description: 'When TRUE the destroy will be fired instead of apply'
        type: boolean
        required: true
        default: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform plan & apply
    runs-on: ubuntu-latest
    if: ${{ inputs.skip_terraform != true }} 
    steps:
    - name: Checkout tf code in runner environment
      uses: actions/checkout@v3.5.2

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Setup Tfenv
      uses: rhythmictech/actions-setup-tfenv@v0.0.4

    - name: Terraform init
      env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Init**"
        make init
        
        echo "** Running Terraform Validate**"
        terraform validate
      working-directory: ${{ github.event.inputs.tfpath }}

    - name: Terraform plan and apply
      env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      if: ${{ inputs.destroy != true }}
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"        
        echo "** Running Terraform Plan**"
        make plan
        echo "** Running Terraform Apply**"
        make apply
      working-directory: ${{ github.event.inputs.tfpath }}

    - name: Upload artifacts
      if: ${{ inputs.tfpath && inputs.destroy != true }}
      uses: actions/upload-artifact@v3
      with:
        name: ansible_inventory_file
        path: ${{ github.workspace }}/lab-kafka/ansible-aws-inventory/inventory.ini

    - name: Terraform Destroy
      if: ${{ inputs.tfpath && inputs.destroy }}
      run: |
        echo "** Running Terraform Destroy**"
        make destroy
      working-directory: ${{ github.event.inputs.tfpath }}

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    if: ${{ inputs.destroy != true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Download inventory file
        uses: actions/download-artifact@v3
        with:
          name: ansible_inventory_file
          path: ${{ github.workspace }}/lab-kafka/ansible-aws-inventory

      - name: See inventory
        run: unzip -o ansible_inventory_file | cat inventory.ini
        working-directory: ${{ github.workspace }}/lab-kafka/ansible-aws-inventory

      - name: Extract bastion_host IP address
        id: extract_bastion_ip
        run: |
          bastion_ip=$(grep 'bastion_host ansible_host=' lab-kafka/ansible-aws-inventory/inventory.ini | awk -F '=' '{print $2}')
          echo "Bastion Host IP: $bastion_ip"
          echo "::set-output name=bastion_ip::$bastion_ip"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ steps.extract_bastion_ip.outputs.bastion_ip }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run ansible ping
        run: |
          cat ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa
          ansible all -m ping
        working-directory: ${{ github.workspace }}/lab-kafka

      - name: Run Ansible Playbooks
        run: ansible-playbook ansible-playbooks/docker.yaml
        working-directory: ${{ github.workspace }}/lab-kafka
